### ISSUE TITLE
Search menu suggestions visibility

### ISSUE THREAD

**Issue by vreuter** [pepkit/pepkit.github.io#3]
The text in the search menu suggestions is difficult to read, e.g.:
<img width="1267" alt="screen shot 2018-10-31 at 1 31 33 pm" src="https://user-images.githubusercontent.com/12036370/47807148-bffcd300-dd11-11e8-9d67-b10b3e31cd6e.png">

**Comment by vreuter** [comment]
When there's a single suggestion it doesn't matter as much since it's in the main window, but when there are multiple suggestions it's more meaningful.

**Comment by nsheff** [comment]
I can confirm this behavior on my system as well.
